version: '3.8'
services:
  dev-database:
    image: postgres:16.3
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    networks:
      - my-networks
networks:
  my-networks: